# Gemfile_A

# Specify the Ruby version
ruby '2.7.3'

# Use gems from RubyGems
source 'https://rubygems.org'

# Rails gem from RubyGems
gem 'rails', '6.1.4'

# Import Gemfile_B
eval_gemfile 'nest/Gemfile'
